# require_recipe 'loadbalancer'
# require_recipe 'quick-test'
# require_recipe 'collectd-tweaks'
# require_recipe 'cron'
# require_recipe 'swap'
# require_recipe 'encoding'
require_recipe 'passenger-env'
